### ISSUE TITLE
dm-paperclip 2.3.0 with Merb 1.1 and Bundler 0.9.16

### ISSUE THREAD

**Issue by dataday** [krobertson/dm-paperclip#6]
$ gem env
RubyGems Environment:
- RUBYGEMS VERSION: 1.3.6
- RUBY VERSION: 1.8.7 (2010-01-10 patchlevel 249) [i686-darwin10]
- INSTALLATION DIRECTORY: /opt/local/lib/ruby/gems/1.8
- RUBY EXECUTABLE: /opt/local/bin/ruby
- EXECUTABLE DIRECTORY: /opt/local/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - x86-darwin-10
- GEM PATHS:
  - /opt/local/lib/ruby/gems/1.8
  - /Users/x/.gem/ruby/1.8
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :benchmark => false
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - http://rubygems.org/

$ bundle install
...
Using dm-paperclip (2.3.0) from system gems
...

$ bundle show dm-paperclip
/opt/local/lib/ruby/gems/1.8/gems/dm-paperclip-2.3.0

$ bundle check
The Gemfile's dependencies are satisfied

However, I'm getting a standardError via bundler everytime the gem list is refreshed on page refresh:

/opt/local/lib/ruby/gems/1.8/gems/bundler-0.9.16/lib/bundler/resolver.rb:163:in `resolve': Could not find gem 'dm-paperclip (>= 2.3, runtime)' in the gems available on this machine. (Bundler::GemNotFound)

This doesn't happen with other gems installed via bundler.

I also ran rake local to dm-paperclip and get the following 

$ rake
(in /usr/local/lib/ruby/gems/1.8/gems/dm-paperclip-2.3.0)
/opt/local/bin/ruby -I"lib:dm-paperclip" "/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb" "test/attachment_test.rb" "test/geometry_test.rb" "test/integration_test.rb" "test/iostream_test.rb" "test/paperclip_test.rb" "test/storage_test.rb" "test/thumbnail_test.rb" 
/opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- shoulda (LoadError)
    from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from ./test/helper.rb:3
    from ./test/attachment_test.rb:1:in `require'
    from ./test/attachment_test.rb:1
    from /opt/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in`load'
    from /opt/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5
    from /opt/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `each'
    from /opt/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5
rake aborted!
Command failed with status (1): [/opt/local/bin/ruby -I"lib:dm-paperclip" "...]

**Comment by dataday** [comment]
Fixed.. am moving my eye towards bundler.... GemFile syntax updated to 

gem "dm-paperclip", ">= 2.3", :path => '/opt/local/lib/ruby/gems/1.8/gems'

all is well again
